services:
  - type: web
    name: cv-mk
    runtime: python
    plan: free
    buildCommand: apt-get update -y && apt-get install -y fonts-dejavu-core && pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
