services:
  - type: web
    name: cv-mk
    runtime: python
    plan: free
    buildCommand: apt-get update -y && apt-get install -y fonts-dejavu-core libpango-1.0-0 libpangocairo-1.0-0 libharfbuzz0b libffi-dev libcairo2 libgdk-pixbuf2.0-0 shared-mime-info && pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
